### ISSUE TITLE
Setup in lxplus

### ISSUE THREAD

**Issue by francescobrivio** [fabioespinosa/runregistry_api_client#3]
Dear @fabioespinosa and @avivace,
while setting up the runregistry api on `lxplus7` I noticed two errors in the README:

- `pip install runregistry` should be replaced by `pip3 install runregistry --user`
- The link to the CERN ticket explaining how to use python3 on lxplus is broken and should be replaced with: https://cern.service-now.com/service-portal?id=kb_article&sys_id=3554cdc50a0a8c0800e89d3ccb5ed4a7

**Comment by avivace** [comment]
Thanks @francescobrivio ! I've updated the link but I'm not sure what's the rationale behind using `--user` while being in a virtual env..

**Comment by francescobrivio** [comment]
> Thanks @francescobrivio ! I've updated the link but I'm not sure what's the rationale behind using `--user` while being in a virtual env..

You are right, I did not use the virtual env thus I needed the `--user`!

**Comment by francescobrivio** [comment]
+1
